1.

In [ ]:
print(1 + 1)
print(type(2)) 
print(type(2.5)) 

x = "Hola a todos"
print(type(x)) 

2
<class 'int'>
<class 'float'>
<class 'str'>


2.


In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 10]
print(len(l1))

print(l1[0]) 


print(l1 + l2) 

print(2 * l1) 

5
1
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


3.

In [ ]:
import numpy as np

l1_arreglo = np.array(l1)
l2_arreglo = np.array(l2)

print(l1_arreglo + l2_arreglo) 
print(2 * l1_arreglo)          
print(0.5 * l2_arreglo)        

[ 7  9 11 13 15]
[ 2  4  6  8 10]
[3.  3.5 4.  4.5 5. ]


4.

In [ ]:
lista = [i for i in range(10, 30)]
arreglo_20 = np.array(lista)



matriz_5x4 = arreglo_20.reshape(5, 4) 
print(matriz_5x4)

matriz_10x2 = arreglo_20.reshape(10, 2)
print(matriz_10x2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]
